before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ReODcn3wqotB+F4Mv/FynuByeUKSFLX+dcEIoVsqLWufDhExaKFydzGA0ym32ftf+meYEfZ7sqyxAhZ8TMBEwq9lWQSeWqkyMdgnPLCV3NStaHJbwTjcOqN2d0tFH9XeKBWF2Bq0ICsOrE1LlhJtKoGr+NR/gSQ8mKUC9Rp4I1CbJEN8RfqhsRudd6GgwT8SyUNzkjHp8RQmJWqu9BbhpDra3YVN6XWgkJYhXmXbxImlKM5dGE7ITc+i+DDLLfqXNsCjy7R95GbwoT7ZJaCYjDG+2fv7HLqWkOvAw8lNTuYkZrtNP3WtpzwAetK6KVLOoGPRnfIct+kXnQ5bcS2YbYv6JCPfISrNu9zMSDmUZIJreHBbY6LnJ1OhbtYpfrDCDLKC1LgNaUhLQrfzVQ1hRYnugPkwQaDKd1HgpdnwW73Ve8VeOHaLDxxJqvwQLmaBRimm/VjzP3WTnTMyfnc6TU0g0mWZ0YbCqT38alEyU70ZW4gptHiLOOx2FI+KiON56JiUbE7oRas947pNZCAXgNS3NWnLn+Va1Sisn/qDERrqFkVSmBIkUMCLD+Rio/6EZ16JjsO55Lw5tk/1e6FB1iYO3DfsyII/zS1MlBai5uC/vddlmrEDsyy1oD+oxR/GQeuqtnkJWZ9mmfXq7l0jBq7sTIQB/3dEwgCy2DtYe2o= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
